### ISSUE TITLE
Empty shopping cart when using the browsers back button

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware5#102]
**Describe the bug**
When you are on the (hpp) redirect page and presses on the browsers back button the shopping cart is emptied. When you use the link 'go back to merchant website' the shopping bag is still available

**To Reproduce**
1. Add some items to the basket
2. Select a redirect payment method
3. Place order and get redirected to the Adyen hpp
4. Press the browsers back button.

**Expected behavior**
Shopping bag stays available

**Comment by cyattilakiss** [comment]
Hi @wannevancamp ,

Thank you for opening this issue.

This is unfortunately a behaviour that is expected. As soon as the customer places the order and being redirected to the redirect page, shopware will create an order and therefore clear the cart. 

The difference between the "go back to merchant website" button and the browser back button is that the first one redirects the customer back to a returnUrl that we provided and if that url is hit then it can cancel the order and reopen the cart with the same items as before while the browser back button doesn't provide any extra info so it would be the same if the customer just typed in the webshop url by hand.

With this approach we make sure that the customer cannot change the cart while paying and that the order will be created even if the customer is not redirected back to the success page at the end due to any error like network or issuer error.

I am happy to hear your thoughts about it, also do you maybe know what percentage of your customers face this issue? Do you get a lot of complains for this? Is there any other way (idea) of solving this issue for example with a button that says "cancel my previous order" whenever the customer redirects back and the payment is not done yet?

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @wannevancamp ,

I will close this issue for now but I am still happy to hear your thoughts about it, also do you maybe know what percentage of your customers face this issue? Do you get a lot of complains for this? Is there any other way (idea) of solving this issue for example with a button that says "cancel my previous order" whenever the customer redirects back and the payment is not done yet?

Best,
Attila
Adyen
