### ISSUE TITLE
When you paid using bancontact, you get redirected to the login page instead of the success page

### ISSUE THREAD

**Issue by jensvandorpe** [Adyen/adyen-shopware5#106]
**Describe the bug**
When you paid using bancontact, you get redirected to the login page instead of the success page

**Comment by wannevancamp** [comment]
@acampos1916 , this seems to be a project specific problem. We will have a further look at it. For now this can be closed.

**Comment by acampos1916** [comment]
Thanks for the update @wannevancamp

**Comment by wannevancamp** [comment]
@acampos1916 , after doing a some research this seems NOT a project specific problem. I can reproduce this on a clean Shopware 5.6.9 environment. For soms unknown reason the Shopware session will reset when using the Bancontact RedirectShopper method. Other RedirectShopper payment method does not have this issue. Because the customer doesn't land on the success page the sales statistics are messed up and incorrect.
