### ISSUE TITLE
paymentData missing in the /payments/details request

### ISSUE THREAD

**Issue by ataberkylmz** [Adyen/adyen-shopware5#108]
**Describe the bug**

`/payments` request was a success and `paymentData`, `MD`, `PaReq` and `redirectUrl` returned in the response all together with `RedirectShopper` action. Server/instance redirected shopper to bank's 3DS1 challenge page correctly and challenge completed correctly. Returned to Shopware 5 instance with `MD` and `PaRes`. Then the server/instance made the `/payments/details` call with `MD` and `PaRes` however `paymentData` key was set to nothing "". This resulted in error in Adyen's side and the payment stuck in Offers section as the payment has never finalized/completed.

This might be an issue related to session variables as `paymentData` is stored in the session instead of in the database. Check the corresponding lines: https://github.com/Adyen/adyen-shopware5/blob/1.6.0/Components/Manager/AdyenManager.php#L35-L61

The session problem might also be the root cause of the issue https://github.com/Adyen/adyen-shopware5/issues/106.

**Comment by jensvandorpe** [comment]
@acampos1916 could you look into this, how do you handle this in other plugins?

**Comment by acampos1916** [comment]
Hello @jensvandorpe,

I checked what @ataberkylmz describes and indeed the issues seems to be [here](https://github.com/Adyen/adyen-shopware5/blame/master/Controllers/Frontend/Process.php#L158), as he describes the payment data is being fetched from the session, which doesn't always work. By the time the user is redirected back to the store the session could be terminated, or the browser could close it due to the SameSite cookie policy, etc.

In the Shopware 6 plugin the payment response is [stored in the database after the initial `/payments` call](https://github.com/Adyen/adyen-shopware6/blob/master/src/Handlers/PaymentResponseHandler.php#L126) and [queried right before the `/payments/details` call](https://github.com/Adyen/adyen-shopware6/blob/master/src/Service/PaymentDetailsService.php#L103).
