### ISSUE TITLE
Skip report notifications

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware5#111]
**Describe the bug**
When an unsupported notification is send to the plugin there is no `[accepted]` in the response. 
For example _Report notifications_

Fix in Shopware 6 plugin: https://github.com/Adyen/adyen-shopware6/blob/develop/src/Service/NotificationReceiverService.php#L271-L274

**To Reproduce**
1. Adyen customer area send REPORT notification
2. Plugin can't handle this type of notification
3. Plugin returns `[notification save error]` instead of `[accepted]`
4. Adyen customer area mentions that notifications are not accepted well.

**Expected behavior**
@acampos1916 , I'm not sure 100% about this:
When a notifications can't be handle correctly the plugin must catch the error and always return `[accepted]` instead of returning the error.

Currently there is validation for the 'existence of an order' when creating the notification and when processing the notification. The validation when creating a notification is not needed: https://github.com/Adyen/adyen-shopware5/blob/develop/Components/Builder/NotificationBuilder.php#L64-L68

**Comment by bortefi** [comment]
@acampos1916 

Currently the following responses are sent from calling /notification/adyen call:

* `'[Invalid or missing auth]'` (failed auth)
* `'[wrong hmac detected]'`  (failed HMAC validation)
* `'[notification save error]'` (issue during notification processing)
* `'[accepted]'` (call was processed)

Since sending back a response something else than `'[accepted]'`would  stop the Adyen notifications center,
Is it more prudent to treat it more like a webhook and always send `'[accepted]'` back when the call has been received?

Or to split it in:
1. on failed authentication or HMAC: sent the error response
2. in other cases send back `'[accepted]'`

**Comment by acampos1916** [comment]
Hey @bortefi,

Coincidentally I'm taking a look at #81 which also touches up on this subject. Indeed all responses should return `[accepted]` if the authentications are valid. In that case your proposal is the desired way.
