### ISSUE TITLE
Payment data not lost on selecting a shipping method

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware5#134]
**Describe the bug**
When changing the shipping method you have to reenter the payment data because the component is replaced with Ajax. This is not user-friendly. This ticket in an extension on #126 

**To Reproduce**
1. Go to the payment selection step
2. Fill in the payment data of a component
3. Switch shipping method
4. The filled in data of the payment component is empty

**Expected behavior**
You expect the payment component to keep the filled in data.

**Comment by Suzell** [comment]
@acampos1916 @peterojo can we help Meteor here think of a solution?

**Comment by acampos1916** [comment]
Hello @wannevancamp, I was just testing this. Indeed it isn't user-friendly.

How about listening for the on change event of the shipping methods and trigger an Ajax call to the saveShippingPayment endpoint so that the payment method selection and data is saved before the shipping method's ajax call is executed?

**Comment by acampos1916** [comment]
Fixed in #151
