### ISSUE TITLE
HMAC Validation does not seem to be working on v2.0.0

### ISSUE THREAD

**Issue by Suzell** [Adyen/adyen-shopware5#182]

**Comment by TaiKamilla** [comment]
Hey @Suzell 
Is this about notifications not working in v3.2.0 (Adyen plugin)?

**Comment by logeecom** [comment]
Hi all, 

Our team checked the latest plugin version (v3.8.0), and the webhooks on the test environment are working as expected.

The HMAC configuration is directly related to the [notifications/webhooks](https://docs.adyen.com/development-resources/webhooks) feature, where HMAC configuration is used for validation of the notification requests. 

Please note that HMAC configuration is used in combination with the (basic) authentication for the notifications username and password, where the username and password validity is checked before HMAC signature validity. Therefore, the plugin must have a valid configuration for notification username/password and HMAC key.

Please also make sure that the notifications configuration is correct for a selected environment (the notifications configuration can be checked as described in [Notification webhooks | Adyen Docs](https://docs.adyen.com/development-resources/webhooks#test-and-go-live)). 

Our suggestion is to close this ticker since the problem with HMAC validation is not present in the latest version.

**Comment by adyen-integrations-support** [comment]
Hi all,

Our team checked the latest plugin version (v3.8.0), and the webhooks on the test environment are working as expected.

The HMAC configuration is directly related to the [notifications/webhooks](https://docs.adyen.com/development-resources/webhooks) feature, where HMAC configuration is used for validation of the notification requests.

Please note that HMAC configuration is used in combination with the (basic) authentication for the notifications username and password, where the username and password validity is checked before HMAC signature validity. Therefore, the plugin must have a valid configuration for notification username/password and HMAC key.

Please also make sure that the notifications configuration is correct for a selected environment (the notifications configuration can be checked as described in [Notification webhooks | Adyen Docs](https://docs.adyen.com/development-resources/webhooks#test-and-go-live)).

Our suggestion is to close this ticket since the problem with HMAC validation is not present in the latest version.
