### ISSUE TITLE
PSP Reference is not showing after checkout

### ISSUE THREAD

**Issue by d-pihale** [Adyen/adyen-shopware5#217]
**Describe the bug**
after finishing the order in shopware the psp reference is not inserted into the field of the transaction number. Instead of the PSP reference from adyen an internal ID from Shopware is used. See on the attached picture of our test shop.

**To Reproduce**
Do a test checkout with any payment method.

**Expected behavior**
we need the adyen psp refernce shown on the checkout

**Screenshots**
![image](https://user-images.githubusercontent.com/108343282/176179868-6f0c4e81-eb37-4ab4-bba9-2a726eb5a504.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: edge chromium
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by teodoratimoti** [comment]
Hello, 

Thank you for reaching out.

Unfortunately, this is not possible at the moment because the plugin gets Adyen PSP reference asynchronously via [the webhooks](https://docs.adyen.com/development-resources/webhooks) upon the [payment authorization](https://docs.adyen.com/account/payments-lifecycle?utm_source=ca_test#authorised) and/or capture. There is no guarantee that the payment authorization webhook will reach the plugin before the final checkout order thank you page.

Please note that eventually (upon webhook receiving and processing) the order PSP Reference will be assigned to the Shopware order. At this moment we can only advise you to take advantage of Adyen_Notification_Process_Authorisation and Adyen_Notification_Process_Capture custom [events](https://developers.shopware.com/developers-guide/event-guide/) that the Adyen plugin fires before the PSP reference is set on the order instance.

Best regards,

Adyen team

**Comment by adyen-integrations-support** [comment]
Hi @olga-adyen,

If this issue is resolved, please close it.

Thank you
