### ISSUE TITLE
Version 3.9.0 When cookies declined payment methods do not show

### ISSUE THREAD

**Issue by DanCarlyon** [Adyen/adyen-shopware5#222]
**Describe the bug**
Using Adyen version 3.9.0, When a user declines cookies, the payment methods do not show during the checkout, preventing a user from checking out

Before accepting or declining cookies
<img width="1379" alt="Screenshot_20_10_2022__11_38" src="https://user-images.githubusercontent.com/4364774/197140463-532e5184-8e4e-447a-bf50-5c411c161cdf.png">

After Declining cookies
<img width="1394" alt="Screenshot_20_10_2022__11_36" src="https://user-images.githubusercontent.com/4364774/197140536-d64366bc-e9d8-44f6-9979-e9093430062c.png">

**To Reproduce**
1. Add a product to the basket
2. Decline cookies
3. Navigate through the checkout process
4. See issue with no payment methods showing

**Expected behavior**
When a user declines cookies, they should still be able to check out with the technical/required cookies

**Screenshots**
Screenshots provided above in the description of the issue

**Desktop:**
 - OS: MacOS & Windows
 - Browser MacOS Chrome Version 105.0.5195.125, Windows Chrome Version 106.0.5249.119

**Additional context**
N/A

**Comment by teodoratimoti** [comment]
Hello @DanCarlyon,

Thank you for reaching out.

Please note that the Adyen plugin requires explicit cookie usage consent in order to allow payment.

The Adyen plugin uses the [standard Shopware cookie consent manager](https://developers.shopware.com/developers-guide/cookie-consent-manager/#dealing-with-the-localstorage) and adds its required cookies to the technical group of Shopware cookies that customers can choose to accept or reject.

By rejecting cookies, the merchant also rejects technical cookies, in other words, it rejects the uninterrupted use of data from the client session, which is necessary for the normal functioning of the plugin and this will also prevent the normal functioning of the Shopware store.

Therefore, it is necessary to accept cookies in order to proceed with the payment.

Thank you,

Best regards.

**Comment by masgo** [comment]
I am voting to reopen this. This limitation seems like a bad design choice. Other payment methods, like PayPal, do not have this limitation. They work without the need for cookies. 

If cookies are really really needed (which I doubt), then the consent implementation should be different. Adyen should ask the customer during the checkout process, where the payment methods are selected, if the user consents to the cookie in order to use credit card (and other adyen methods). 

Or, the adyen cookie should be added as a required cookie and bet set even if the user clicks on "reject". Since a webshop without a payment option is (more or less) useless.
