### ISSUE TITLE
Placeholder names in Adyen Transaction list

### ISSUE THREAD

**Issue by DanCarlyon** [Adyen/adyen-shopware5#223]
**Describe the bug**
Plugin version 3.9.0
Payment details coming through to adyen appear to have a placeholder name for the Cardholder name/Shopper Name
![image](https://user-images.githubusercontent.com/4364774/197204655-d2be1afc-97d4-4c28-9adb-c7180092d316.png)

**To Reproduce**
1. Place orders using Adyen payment methods
2. Review adyen

**Expected behavior**
Custom names appear correctly in the adyen transaction list

**Screenshots**
See Above

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
This happens in Both Live and Test

**Comment by adyen-integrations-support** [comment]
Hello @DanCarlyon,

Thank you for reaching out.

Our team will check this issue and we will get back to You with new information.

Thank you,

Best regards.

**Comment by adyen-integrations-support** [comment]
Hello @DanCarlyon ,

Please note that our team is finalizing the investigation.

We will get back to you with new information as soon as possible.

Best regards.

**Comment by DanCarlyon** [comment]
Hi @adyen-integrations-support 

How's it going, any update on this one? :)

**Comment by adyen-integrations-support** [comment]
Hello,

Please note that our team has successfully reproduced this issue locally and we have found the following problem:
Shopware 5 Adyen integration sends shopper data correctly, but this data is not displayed in the Adyen transactions table.

Our team needs more time to confirm what is the root of the issue.

We will notify you as soon as the issue is solved.

Thank you,

Best regards.

**Comment by adyen-integrations-support** [comment]
Hello @DanCarlyon ,

Please note that in Adyen Shopware 5 plugin, the credit card web component is not configured to enable shoppers to enter the cardholder name.
The credit card web component has multiple optional configurations and there are possible solutions to the reported problem.
Since both of these changes would require additional analysis this is considered as a change request.

Thank you very much for bringing this to our attention, the product team will review it and process it further.
We will keep you posted about the status of this change request.

Thank you,
Best regards.

**Comment by RobertJohnsonadyen** [comment]
Hi Team,

Appreciate there is a bit of work here but as it is hindering the finance teams ability to manage payments in the back end so can we prioritise this for them please?

Regards, Rob
