### ISSUE TITLE
Our merchant found a potential topic with SE Card payments

### ISSUE THREAD

**Issue by marcDavies56211** [Adyen/adyen-shopware5#228]
**Describe the bug**
1) The comment in " PaymentMethod.php " [AdyenPayment/Models/Payment/PaymentMethod.php]  file explains that " Standardize credit card code for Sweden,  Adyen returns value as scheme_card instead of scheme_credit_card for SW ". 

But actually the parameter returned is " scheme_cards " and not " scheme_card "

2. When Adyen value is scheme_card, in response we didn't get the value as  scheme_credit_card

**To Reproduce**
1. Create a merchant who uses adyen card component via shopware plug in for country = SE
2. Set the payment method up in adyen as normal and ensure correct configs for the payment method etc
3. Attempt to render the component....you will see that it will not. 

**Expected behavior**
Card component renders even if shopper country is SE

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**

3. The merchant made a small change to fix the issue:

"We changed the Adyen returns value as scheme_cards instead of scheme_card in your partner code and we were able to get the value correctly in our response. 

After we made the change as per point number 3 the Credit Card is displaying for Sweden Country"

**Comment by marcDavies56211** [comment]
Hi,

It was Shopware version 5.6.6 and plugin 3.9.9.

Best wishes,
Marc


---
Marc Davies
Implementation Consultant

contact: adyen.com/contact <https://www.adyen.com/contact>

Adyen Berlin
Jägerstrasse 27
10117 Berlin, Germany

 <https://www.adyen.com/>

**Comment by logeecom** [comment]
Hello @marcDavies56211,

Please note that the reported issue has been addressed and fixed in the new version of the module (v4.x).

We would suggest updating the module in your shop to the latest version 

The version 4.X is an enhanced and updated iteration of the module you're presently using. We recommend reviewing the new features and improvements.

If you choose to upgrade to the latest version, we would strongly recommend going over the Migration notes for you to migrate to the new version as smoothly as possible.

Plugin link: https://github.com/Adyen/adyen-shopware5/releases 

Migration notes: https://github.com/Adyen/adyen-shopware5/wiki#migrating-from-the-older-version 

If you have any further questions, please do not hesitate to let us know.

Kind regards.
