### ISSUE TITLE
configuration problem in step 2 after the installation of the new version 4.1.0

### ISSUE THREAD

**Issue by hakimdjabri** [Adyen/adyen-shopware5#229]
**Describe the bug**

configuration problem in step 2 (Merchant account) validation after the installation of the plugin version 4.1.0 in shopware 5.7.7

**To Reproduce**
1. Go to adyen configuration plugin Setup
2. Click on connect  after copying the API key
3. in step to (Merchant account) when I choose my marchent account I clicked next and the error apear
4. See error below in the screenshot

**Expected behavior**
go to the next step payment methode

**Screenshots**
![image](https://github.com/Adyen/adyen-shopware5/assets/47453138/97794907-dbc1-4d22-95f0-0180699d5eac)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser : chrome
 - Version:  120.0.6099.71

**Comment by logeecom** [comment]
Hello @hakimdjabri 

Yes, there was indeed an issue with the webhook validation. Can you please try to regenerate the new API key and try to connect the integration?
Please make sure to have enabled all [necessary roles](https://github.com/Adyen/adyen-shopware5/wiki#step-2-generate-an-api-key).

Also, if you still face the same issue again please note that In order to further investigate this issue, our team would need to log into your shop and examine the reported problem.

Please, submit your query through our regular support channels by going to https://www.adyen.help/hc/en-us/requests/new or by sending an e-mail to [support@adyen.com](mailto:support@adyen.com). Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.

Please note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having.

If you have any questions or concerns, please let us know.

Kind regards.

**Comment by hakimdjabri** [comment]
> Hello @hakimdjabri
> 
> Yes, there was indeed an issue with the webhook validation. Can you please try to regenerate the new API key and try to connect the integration? Please make sure to have enabled all [necessary roles](https://github.com/Adyen/adyen-shopware5/wiki#step-2-generate-an-api-key).
> 
> Also, if you still face the same issue again please note that In order to further investigate this issue, our team would need to log into your shop and examine the reported problem.
> 
> Please, submit your query through our regular support channels by going to https://www.adyen.help/hc/en-us/requests/new or by sending an e-mail to [support@adyen.com](mailto:support@adyen.com). Alternatively, you can also submit your request through the Support section of your Adyen Customer Area.
> 
> Please note that you will first communicate with the first level of support, after which the second level of support will be involved. Make sure to provide a detailed explanation of the issue you are having.
> 
> If you have any questions or concerns, please let us know.
> 
> Kind regards.

@logeecom @teodoratimoti  it works now, thank's a lot
