### ISSUE TITLE
Missing support for language shops

### ISSUE THREAD

**Issue by sheitmeier** [Adyen/adyen-shopware5#232]
**Describe the bug**
Using adyen in language shops, that have a main shop, is creating an infinite loop calling /checkout/shippingPayment in these shops.

**To Reproduce**

1. Create a shopware instance with one main store and a language variant of this store.
2. Enter checkout in the language store.
3. Go to /checkout/shippingPayment step in checkout.

**Expected behavior**
The payment means configured for the main shop should be shown, since it is not possible to configure the module separately for language shops.

**Additional context**
From what we have seen so far, the issue is caused, because the module relies on the id retrieved via Shopware()->Shop()->getId() to get the checkout configuration. But since you cannot configure the module for these types of shops, the configuration cannot be loaded.
Since the module cannot load the checkout config, the enriched payment means are empty and the redirect in EnrichUserAdditionalPaymentSubscriber is executed.

**Comment by logeecom** [comment]
Hey @sheitmeier,

Thank you for reaching out.
Our team will check this issue and get back to you.

Best regards.

**Comment by logeecom** [comment]
Hello @sheitmeier,

Note that our team has reviewed your inquiry and we are pleased to let you know that we have fixed the reported problem.

The Adyen plugin divides contexts between the main shop and subshops. Language shops follow the same configuration as their main shop. Thus, throughout the code used in the checkout process where Shopware()->Shop()->getId() is utilized, it should be verified whether the current store is a language shop. In such cases, if Shopware()->Shop()->getMain() is not null, it indicates that the current store is a language shop, and therefore, the configuration for the main shop should be employed.

Note that these changes will be live with the next release.

Here is the zip so that you can apply changes and fix the issue before officially releasing the new plugin version:
[AdyenPayment.zip](https://github.com/Adyen/adyen-shopware5/files/14385541/AdyenPayment.zip)

If you have any further questions, please let us know.

Kind regards.

**Comment by sheitmeier** [comment]
Thanks a lot for providing feedback and for the fix.
