### ISSUE TITLE
[PW-2505] Add separate Notifications HMAC, user and password, and API key config fields for test environment

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-shopware5#27]
**Describe the bug**
The plugin is using one set of Notifications HMAC, user, password, and API key configs both for live and test scenarios. A new set has to be added to verify notifications when test mode is enabled.

**To Reproduce**
1. Test the plugin connection and notification receiving in live and test mode, the requests will be made with the same set of config values.

**Expected behavior**
New set of config fields should be present to query the test/live mode on notification receiving and plugin requests.

**Comment by wannevancamp** [comment]
Hi @acampos1916 ,

I don't think this will make the configuration of the plugin more clear. 

Some notices:

- What is the expected behaviour of the API test button? Will the test call check the test or the live endpoint? Maybe a new button 'test API connection live' should be added.
- What are the new required fields? If we separate the config fields we will have 5 extra required field which is not user friendly.

When we add those configuration fields and new test button the simplified configuration will double in size.

I suggest to clarify this in the documentation. I would like to hear your opinion on this.

**Comment by acampos1916** [comment]
Hey @wannevancamp,

The test button's expected behavior would be to try to connect to the live or test endpoint depending on the state of the `environment` configuration field.

Adyen's test and live accounts for the merchants can have completely different Merchant Account, API key and server communication parameters. So, if we don't provide another set of config fields and merchants want to move from one mode to the other they would have to unset the previous configuration and then set it again if they want to go back.

With new fields they can use the `environment` toggle to switch between configurations and endpoints to use. That's how it is preferred in other plugins as well.
